sonar.projectKey=event-planner-architecture
sonar.projectName=Event Planner Architecture
sonar.sources=src,scripts
sonar.tests=tests
sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.testExecutionReportPaths=reports/sonar-test-report.xml
sonar.coverage.exclusions=src/main.jsx,src/App.jsx,vite.config.js
sonar.sourceEncoding=UTF-8
